/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MultiOutcomeMarketInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "conditionalTokens"
      | "createCategoricalMarket"
      | "createScalarMarket"
      | "markets"
      | "outcomePrices"
      | "resolveMarket"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "MarketCreated" | "MarketResolved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "conditionalTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createCategoricalMarket",
    values: [string, string[], BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createScalarMarket",
    values: [string, BigNumberish, BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "markets", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "outcomePrices",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveMarket",
    values: [BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "conditionalTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCategoricalMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createScalarMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "markets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "outcomePrices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveMarket",
    data: BytesLike
  ): Result;
}

export namespace MarketCreatedEvent {
  export type InputTuple = [
    marketId: BytesLike,
    question: string,
    marketType: BigNumberish,
    outcomeCount: BigNumberish
  ];
  export type OutputTuple = [
    marketId: string,
    question: string,
    marketType: bigint,
    outcomeCount: bigint
  ];
  export interface OutputObject {
    marketId: string;
    question: string;
    marketType: bigint;
    outcomeCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketResolvedEvent {
  export type InputTuple = [marketId: BytesLike, winningOutcome: BigNumberish];
  export type OutputTuple = [marketId: string, winningOutcome: bigint];
  export interface OutputObject {
    marketId: string;
    winningOutcome: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MultiOutcomeMarket extends BaseContract {
  connect(runner?: ContractRunner | null): MultiOutcomeMarket;
  waitForDeployment(): Promise<this>;

  interface: MultiOutcomeMarketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  conditionalTokens: TypedContractMethod<[], [string], "view">;

  createCategoricalMarket: TypedContractMethod<
    [
      question: string,
      outcomes: string[],
      endTime: BigNumberish,
      oracle: AddressLike
    ],
    [string],
    "nonpayable"
  >;

  createScalarMarket: TypedContractMethod<
    [
      question: string,
      minValue: BigNumberish,
      maxValue: BigNumberish,
      endTime: BigNumberish,
      oracle: AddressLike
    ],
    [string],
    "nonpayable"
  >;

  markets: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, string, boolean, bigint, bigint] & {
        question: string;
        endTime: bigint;
        oracle: string;
        resolved: boolean;
        winningOutcome: bigint;
        marketType: bigint;
      }
    ],
    "view"
  >;

  outcomePrices: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  resolveMarket: TypedContractMethod<
    [marketId: BytesLike, winningOutcome: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "conditionalTokens"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createCategoricalMarket"
  ): TypedContractMethod<
    [
      question: string,
      outcomes: string[],
      endTime: BigNumberish,
      oracle: AddressLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createScalarMarket"
  ): TypedContractMethod<
    [
      question: string,
      minValue: BigNumberish,
      maxValue: BigNumberish,
      endTime: BigNumberish,
      oracle: AddressLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "markets"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, string, boolean, bigint, bigint] & {
        question: string;
        endTime: bigint;
        oracle: string;
        resolved: boolean;
        winningOutcome: bigint;
        marketType: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "outcomePrices"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "resolveMarket"
  ): TypedContractMethod<
    [marketId: BytesLike, winningOutcome: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "MarketCreated"
  ): TypedContractEvent<
    MarketCreatedEvent.InputTuple,
    MarketCreatedEvent.OutputTuple,
    MarketCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MarketResolved"
  ): TypedContractEvent<
    MarketResolvedEvent.InputTuple,
    MarketResolvedEvent.OutputTuple,
    MarketResolvedEvent.OutputObject
  >;

  filters: {
    "MarketCreated(bytes32,string,uint8,uint256)": TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;
    MarketCreated: TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;

    "MarketResolved(bytes32,uint256)": TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;
    MarketResolved: TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;
  };
}
