/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace OrderBookV2 {
  export type OrderStruct = {
    maker: AddressLike;
    marketId: BigNumberish;
    outcomeId: BigNumberish;
    amount: BigNumberish;
    price: BigNumberish;
    isBuy: boolean;
    filled: boolean;
  };

  export type OrderStructOutput = [
    maker: string,
    marketId: bigint,
    outcomeId: bigint,
    amount: bigint,
    price: bigint,
    isBuy: boolean,
    filled: boolean
  ] & {
    maker: string;
    marketId: bigint;
    outcomeId: bigint;
    amount: bigint;
    price: bigint;
    isBuy: boolean;
    filled: boolean;
  };
}

export interface OrderBookV2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelOrder"
      | "cancelled"
      | "getOrder"
      | "getOrderCount"
      | "orders"
      | "placeOrder"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "OrderCancelled" | "OrderFilled" | "OrderPlaced"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelled",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrderCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "orders",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "placeOrder",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancelled", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getOrder", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getOrderCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "orders", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "placeOrder", data: BytesLike): Result;
}

export namespace OrderCancelledEvent {
  export type InputTuple = [orderId: BigNumberish];
  export type OutputTuple = [orderId: bigint];
  export interface OutputObject {
    orderId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderFilledEvent {
  export type InputTuple = [orderId: BigNumberish];
  export type OutputTuple = [orderId: bigint];
  export interface OutputObject {
    orderId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderPlacedEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    maker: AddressLike,
    marketId: BigNumberish,
    outcomeId: BigNumberish,
    amount: BigNumberish,
    price: BigNumberish,
    isBuy: boolean
  ];
  export type OutputTuple = [
    orderId: bigint,
    maker: string,
    marketId: bigint,
    outcomeId: bigint,
    amount: bigint,
    price: bigint,
    isBuy: boolean
  ];
  export interface OutputObject {
    orderId: bigint;
    maker: string;
    marketId: bigint;
    outcomeId: bigint;
    amount: bigint;
    price: bigint;
    isBuy: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OrderBookV2 extends BaseContract {
  connect(runner?: ContractRunner | null): OrderBookV2;
  waitForDeployment(): Promise<this>;

  interface: OrderBookV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelOrder: TypedContractMethod<
    [orderId: BigNumberish],
    [void],
    "nonpayable"
  >;

  cancelled: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  getOrder: TypedContractMethod<
    [orderId: BigNumberish],
    [OrderBookV2.OrderStructOutput],
    "view"
  >;

  getOrderCount: TypedContractMethod<[], [bigint], "view">;

  orders: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, boolean, boolean] & {
        maker: string;
        marketId: bigint;
        outcomeId: bigint;
        amount: bigint;
        price: bigint;
        isBuy: boolean;
        filled: boolean;
      }
    ],
    "view"
  >;

  placeOrder: TypedContractMethod<
    [
      marketId: BigNumberish,
      outcomeId: BigNumberish,
      amount: BigNumberish,
      price: BigNumberish,
      isBuy: boolean
    ],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelOrder"
  ): TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelled"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "getOrder"
  ): TypedContractMethod<
    [orderId: BigNumberish],
    [OrderBookV2.OrderStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOrderCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "orders"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, boolean, boolean] & {
        maker: string;
        marketId: bigint;
        outcomeId: bigint;
        amount: bigint;
        price: bigint;
        isBuy: boolean;
        filled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "placeOrder"
  ): TypedContractMethod<
    [
      marketId: BigNumberish,
      outcomeId: BigNumberish,
      amount: BigNumberish,
      price: BigNumberish,
      isBuy: boolean
    ],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "OrderCancelled"
  ): TypedContractEvent<
    OrderCancelledEvent.InputTuple,
    OrderCancelledEvent.OutputTuple,
    OrderCancelledEvent.OutputObject
  >;
  getEvent(
    key: "OrderFilled"
  ): TypedContractEvent<
    OrderFilledEvent.InputTuple,
    OrderFilledEvent.OutputTuple,
    OrderFilledEvent.OutputObject
  >;
  getEvent(
    key: "OrderPlaced"
  ): TypedContractEvent<
    OrderPlacedEvent.InputTuple,
    OrderPlacedEvent.OutputTuple,
    OrderPlacedEvent.OutputObject
  >;

  filters: {
    "OrderCancelled(uint256)": TypedContractEvent<
      OrderCancelledEvent.InputTuple,
      OrderCancelledEvent.OutputTuple,
      OrderCancelledEvent.OutputObject
    >;
    OrderCancelled: TypedContractEvent<
      OrderCancelledEvent.InputTuple,
      OrderCancelledEvent.OutputTuple,
      OrderCancelledEvent.OutputObject
    >;

    "OrderFilled(uint256)": TypedContractEvent<
      OrderFilledEvent.InputTuple,
      OrderFilledEvent.OutputTuple,
      OrderFilledEvent.OutputObject
    >;
    OrderFilled: TypedContractEvent<
      OrderFilledEvent.InputTuple,
      OrderFilledEvent.OutputTuple,
      OrderFilledEvent.OutputObject
    >;

    "OrderPlaced(uint256,address,uint256,uint256,uint256,uint256,bool)": TypedContractEvent<
      OrderPlacedEvent.InputTuple,
      OrderPlacedEvent.OutputTuple,
      OrderPlacedEvent.OutputObject
    >;
    OrderPlaced: TypedContractEvent<
      OrderPlacedEvent.InputTuple,
      OrderPlacedEvent.OutputTuple,
      OrderPlacedEvent.OutputObject
    >;
  };
}
